# Generated by Django 2.0.3 on 2018-04-02 00:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingEmployment',
            fields=[
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigaAcLabsLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('total_hours', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Liga AC LABS lab',
                'verbose_name_plural': 'Liga AC LABS labs',
            },
        ),
        migrations.CreateModel(
            name='OtherCondition',
            fields=[
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=2096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlannedInternship',
            fields=[
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='internships.Company'),
        ),
        migrations.AddField(
            model_name='plannedinternship',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='students.StudentProfile'),
        ),
        migrations.AddField(
            model_name='othercondition',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_condition', to='students.StudentProfile'),
        ),
        migrations.AddField(
            model_name='existingemployment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='students.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='liga_ac_labs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.LigaAcLabsLab', verbose_name='Liga AC LABS lab'),
        ),
    ]
