# Generated by Django 2.0.3 on 2018-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_summer_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligaaclabslab',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
    ]
