# Generated by Django 3.2.9 on 2021-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_alter_internshipoffer_tags'),
        ('students', '0004_social_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='internships.InternshipOffer'),
        ),
    ]
