# Generated by Django 3.2.11 on 2022-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='reg',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
