# Generated by Django 2.0.3 on 2018-03-29 18:48

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="Used when building the URL for the company's page, e.g. https://practica.ligaac.ro/company/{slug}", unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Short company description', max_length=4096)),
                ('website', models.URLField(blank=True, help_text='Company website', null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('locationUrl', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Location link (Google Maps)')),
                ('logo', models.ImageField(blank=True, help_text="The company's logo in as high a resolution as possible. The display aspect ratio is 10:7.", null=True, upload_to='logos')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the person representing this company', max_length=255)),
                ('email', models.EmailField(help_text='E-mail address of the contact person', max_length=254)),
                ('position', models.CharField(blank=True, help_text='Job title within the company', max_length=255, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='internships.Company')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Job title or project name', max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Internship project description', max_length=4096)),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Technical knowledge required by the company for this job', max_length=4096, null=True)),
                ('is_paid', models.BooleanField(help_text='Checked if students will be paid for the time worked during this internship program')),
                ('capacity', models.IntegerField(help_text='The maximum number of students that will be accepted in this internship program', validators=[django.core.validators.MinValueValidator(1)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internships.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
