# Generated by Django 3.2.9 on 2021-11-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_auto_20211111_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternshipCategory',
            new_name='InternshipTag',
        ),
    ]
