# Generated by Django 3.2.9 on 2021-11-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_rename_internshipcategory_internshiptag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipoffer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='internship_offer', to='internships.InternshipTag'),
        ),
    ]
