# Generated by Django 3.2.10 on 2021-12-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('internships', '0005_alter_internshipoffer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
