# Generated by Django 3.2.11 on 2022-02-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_company_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipoffer',
            options={'verbose_name': 'Offer', 'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='internshiptag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='locationUrl',
        ),
    ]
