# Generated by Django 3.2.12 on 2022-03-31 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_auto_20220208_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Short company description', max_length=8192),
        ),
        migrations.AlterField(
            model_name='company',
            name='visible_for_students',
            field=models.BooleanField(default=False, help_text='When the box is ticked the students can view the company in the application.'),
        ),
    ]
