# Generated by Django 3.2.13 on 2022-06-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_auto_20220331_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AC', 'Automatică și Calculatoare'),
                                                   ('ARH', 'Arhitectură'),
                                                   ('CIM', 'Chimie Industrială și Ingineria Mediului'),
                                                   ('CT', 'Construcții'),
                                                   ('ETcTI', 'Electronică, Telecomunicații și Tehnologii Informaționale'),
                                                   ('IEE', 'Inginerie Electrică și Energetică'),
                                                   ('IH', 'Inginerie din Hunedoara'),
                                                   ('MPT', 'Management în Producție și Transporturi'),
                                                   ('MEC', 'Mecanică'),
                                                   ('SC', 'Științe ale comunicării')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='target_group',
            field=models.ManyToManyField(to='internships.FacultyTag'),
        ),
    ]
