# Generated by Django 3.2.13 on 2022-06-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_auto_20220606_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultytag',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='facultytag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='target_group',
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='target_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offer_target_group', to='internships.facultytag'),
            preserve_default=False,
        ),
    ]
