# Generated by Django 2.0.3 on 2018-04-01 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprefill',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefill', to=settings.AUTH_USER_MODEL),
        ),
    ]
