# Generated by Django 2.0.3 on 2018-04-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_prefill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprefill',
            name='study_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_students', to='users.StudentClass'),
        ),
    ]
