# Generated by Django 2.0.3 on 2018-04-01 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_prefill_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprefill',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefill', to=settings.AUTH_USER_MODEL),
        ),
    ]
