# Generated by Django 3.2.11 on 2022-02-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg',
            field=models.CharField(blank=True, default=None, help_text='Număr matricol', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.studentclass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='StudentPrefill',
        ),
    ]
