# Generated by Django 3.2.11 on 2022-02-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_upt_auth_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='study_class',
        ),
    ]
