# Generated by Django 3.2.12 on 2022-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_studentclass_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
